name: Build and test
on: [push]
jobs:
  native-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - name: setup go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: install dependencies
        run: go get .
      - name: run tests
        run: go test . -tags testing -v
      - name: build
        run: go build -o bin/browser_remote
      - name: keep artifact
        uses: actions/upload-artifact@v4
        with:
          name: browser_remote
          path: app/bin/browser_remote
  add-on:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./add-on
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: add-on/**
      # version in manifest.json must be incremented
      - name: publish
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npx web-ext sign --channel unlisted --api-key="$API_KEY" --api-secret="$API_SECRET"
        env:
          API_KEY: ${{ secrets.FIREFOX_API_KEY }}
          API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
      - name: keep artifact
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: browser_remote.xpi
          path: add-on/web-ext-artifacts/*.xpi
