name: Build and test
on: [push]
jobs:
  native-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - name: setup go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: install dependencies
        run: go get .
      - name: run tests
        run: go test example/remote/internal/native_messaging -tags testing -v
      - name: build
        run: go build -o bin/browser_remote
      - name: keep artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-app
          path: app/bin/browser_remote
  add-on:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./add-on
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: publish
        run: npx web-ext sign --channel unlisted --api-key="$API_KEY" --api-secret="$API_SECRET"
        env:
          API_KEY: ${{ secrets.FIREFOX_API_KEY }}
          API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
      - name: keep artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-add-on
          path: app/web-ext-artifacts/*.xpi
